# Generated by Django 4.1.1 on 2022-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="perks",
            field=models.ManyToManyField(to="experiences.perk"),
        ),
        migrations.AddField(
            model_name="perk",
            name="explanation",
            field=models.TextField(default=""),
        ),
    ]
