# Generated by Django 4.1.1 on 2022-10-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_experience_category_alter_perk_detail_and_more"),
        ("rooms", "0005_alter_room_amenity_alter_room_category_and_more"),
        ("wishlists", "0002_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(
                related_name="wishlists", to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(related_name="wishlists", to="rooms.room"),
        ),
    ]
